### PR TITLE
Add baseview backend to workspace

### PR DESCRIPTION
**Pull request by BillyDM**
I found out cargo isn't happy when you have multiple bin examples that use different dependencies. So the way around this is to keep the existing examples as non-bins, and run this command to run the example with baseview:
```
cargo run --example example_name --no-default-features --features "baseview"
```

### CODE REVIEW

**Comment by geom3trik** [comment]
This looks great! Thank you. One thing I was wondering is whether the EventManager from core can be used now that I've removed the window dependency. Also, what's you're opinion on getting rid of the run() method from Application (for all backends) because it seems a bit pointless. The app could start running as soon as you open a window unless you can think of a reason to keep it?

**Comment by BillyDM** [comment]
I wouldn't get rid of the `run()` method. In audio plugins, you do **not** want to block the current thread. The `tuix_baseview` `Application` includes two extra run methods, `open_parented()` and `open_as_if_parented()`, which don't block the calling thread.

**Comment by BillyDM** [comment]
Oh, the `EventManager` from core works, but for some reason the UI is shifted when the app first opens, but then fixes itself when the window is resized.

**Comment by BillyDM** [comment]
> Oh, the `EventManager` from core works, but for some reason the UI is shifted when the app first opens, but then fixes itself when the window is resized.

Found the problem, I forgot to change `width` to `height` in the constructor.

**Pull request merged**
